### ISSUE TITLE
Todo before release

### ISSUE THREAD

**Issue by viktorstrate** [photoview/photoview-ios#1]
What must be done before releasing it to the App Store

- [x] Support videos
- [x] Pagination / lazy-loading
- ~~Load high-res image in fullscreen and detailed view~~
- [x] fix bug where media is cached when logging out and in as another user

**Comment by sedony23** [comment]
Hi there, I have a pretty big photo library and the app just crashes after launch and doesn't react to input. With less photos it works just fine..

Thanks for the great photoview software though!
